# Generated by Django 4.1.4 on 2023-01-03 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_recipes_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='created_data',
            new_name='created_date',
        ),
    ]
